### ISSUE TITLE
I don't think I am fully understanding this

### ISSUE THREAD

**Issue by Pulceilcane** [Skeli789/Dynamic-Pokemon-Expansion#14]
Hi Skeli
I tried to use this dyamic expansion and cfru but I am getting problems:
first of all I'm going to tell you exactly what I did

I took a blank fr rom
I compiled in this dynamic pokemon expansion (leaving every setting as it was before)
I compiled in cfru, still leaving every setting as default

now I wanted to start editing a map, so i opened Advancemap, but the wild pokemon list is blank and I'm not sure if this is a AM problem, or if I should edit the settings in some way.

Anyway, I appreciate very much your work, thanks

**Comment by Diego-JRH** [comment]
You have to use Advance Map 1.95, since 1.92 doesn't work well with expanded roms. You also have to modify it in order to load the full pokemon list.

**Comment by Garrett-Scott** [comment]
How do you modify AM 1.95 to load the full list?

**Comment by mason101516** [comment]
Open the exe in a hex (a map 1.95) go to 77dd5 and change 9b 01 with 00 05, save it, and it should work (ignore the gibberish at the bottom of the Pokémon selection I don't know the exact number of Pokémon in the rom so that's why it happens)

**Comment by TerrineDefoiegras** [comment]
Hi Skeli, thank you very much for your work ! I have the same issue in advancemap 1.95, I did the change mentioned above on a hex editor, but I'm still having a blank list of wild encounters. I'm using the last version of DPE and CFRU using Leon's Rom Base, with pokémons up to gen 7, and I'm planning to add gen 8 later on.

When using 1.92 I have names but they're all gibberish. Is there something I can do to solve this ?

**Comment by Skeli789** [comment]
You can't fix 1.92, so all you can do is make sure you've actually inserted the data before opening the ROM.
