### ISSUE TITLE
Struggle move

### ISSUE THREAD

**Issue by mason101516** [Skeli789/Dynamic-Pokemon-Expansion#25]
After applying CFRU and DPE to a clean squirrels rom, I made it possible for a wild level 3 sewaddle appear on route one.  So after I did that, all it had was struggle.  That also happened for a wild necrozma.  So then, I made the necrozma level 67, then it had a move.  Only one.  And that one move didn't affect my level 6 bulbasaur.  and I beat it.  Will you fix the moveset issue? or is it my problem?

**Comment by G0LD** [comment]
Before you compile CFRU remove all comment symbols after Chimecho's learnsets from file src/tables/level_up_learnsets.c and compile again

**Comment by mason101516** [comment]
Thank you very much! it worked.

**Comment by TheFruityOne** [comment]
I have the same issue but I've checked the learnsets and nothing is commented out, what do you think I'm missing?

**Comment by TheFruityOne** [comment]
I have now edited out the comments on expand learnsets but now the game crashes as soon as I select a starter, sorry I'm not getting this!

**Comment by Skeli789** [comment]
> I have the same issue but I've checked the learnsets and nothing is commented out, what do you think I'm missing?

You need to the use the CFRU also, otherwise the expanded learnsets won't work
