### ISSUE TITLE
Wondering where to look with regards to changes made to the save format.

### ISSUE THREAD

**Issue by RGamberini** [Skeli789/Dynamic-Pokemon-Expansion#27]
Hello,

I'm attempting to write an external tool to track my Pokedex progress in Pokemon Unbound. I would like to parse the save file to see which Pokemon I've seen.

However while attempting to follow this documentation: https://bulbapedia.bulbagarden.net/wiki/Save_data_structure_in_Generation_III on BulbaPedia. I've found that the save file format has been changed. I would assume that this change stems from the addition of all the new Pokemon coming from Dynamic Pokemon Expansion.

Would you have any resources / bits of code to look at regarding the changes made to the save format to accommodate the extra Pokemon?

I see the `GetSetPokedexFlag` method in [updated_code.c](https://github.com/Skeli789/Dynamic-Pokemon-Expansion/blob/master/src/updated_code.c#L35) but I'm having a hard time following it to where those changes are applied.

Any help would be greatly appreciated.
Thank you.

**Comment by Skeli789** [comment]
Not sure if this helps at all, but the new seen flags are right after the PC Items in memory. So if you find the offset of the PC Items in the save file (which in the ROM is at 0x20257C4), 0x78 bytes later the seen flags start. 0x7D bytes after that the catch flags start. Hope that helps!

**Comment by RGamberini** [comment]
@Skeli789 Thank you so much for the help; that's exactly what I needed to find the offset!

For anyone coming here in the future this is the process I used to find the offset for the PC Items in the save file.
1. Put an item into the PC.
2. Find that item's id in [item.h](https://github.com/Skeli789/Complete-Fire-Red-Upgrade/blob/96113bf1d0a4472f82298a9296678d73d984defe/include/constants/items.h)
3. Look for the hex version of the item in the PC using the format on [BulbaPedia](https://bulbapedia.bulbagarden.net/wiki/Save_data_structure_in_Generation_III#Item_entry)
4. Go 0x79 bytes later and you'll be at the beginning of the seen flags.

For me the offsets were 0x5297 for the items and 0x5310 for the seen flags.

**Comment by NoelDavies** [comment]
@RGamberini We're looking to do this but for full live tracking as we have for all of the vanilla games.

I need to really delve into this to support Radical red and Unbound. - Hit me up on Discord. I'd love to discuss this if possible. Jezzabel#1171
