### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by blooper15** [Skeli789/Dynamic-Pokemon-Expansion#9]
When I tried to do the make command, it told me that I was missing freeimage.dll and libwinthread.dll. after adding them this came up.
![Linker](https://user-images.githubusercontent.com/50726444/60392057-d25e2500-9ac9-11e9-89a4-ffb09e4ea5fe.png)

**Comment by Aioria991** [comment]
I have this error too

C://devkitPro//devkitARM//bin\arm-none-eabi-objdump: 'build/linked.o': No such file
Error: The insertion process could not be completed.
The linker symbol file was not found.

**Comment by Skeli789** [comment]
The missing files have been pushed. It should compile properly now.
